# This is a basic workflow to help you get started with Actions

name: Package and release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Clone project
        uses: actions/checkout@v1
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Package and release
      - uses: BigWigsMods/checkout@v1
        with:
          args: -g retail
